services:
  - type: web
    name: drlaw-backend
    env: python
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:app --workers=2 --timeout=300
    pythonVersion: 3.11.9
    envVars:
      - key: BACKEND_URL
        fromService:
          name: drlaw-backend
          type: web
          property: url
    autoDeploy: true
